### ISSUE TITLE
Rules JSON has bad string error when used in firebase

### ISSUE THREAD

**Issue by ghost** [douglascorrea/angularfire-multi-auth#12]
I faced a warning/error when used your recently updated securityRules.json into firebase database, 

Solution: removing the ending comma resolved the issue securityRules.json line #5

"google"], < -- remove this comma

May I please request to review and update if reproducible.

**Comment by douglascorrea** [comment]
Thanks @appplumbr for reporting the issue

**Comment by ghost** [comment]
Welcome and thanks for updating.

**Comment by leandrocrs** [comment]
For some reason, the bower package is still shipping with this comma.

**Comment by ghost** [comment]
@leandrw please open a new issue with all details version of bower you are using and mark this issue # inside for reference
